- .jscsrc
- .jshintrc
- .travis.yml
- bower.json
- demo/index.html
- gulpfile.js
- package.json
- test/mock-touch-interactions.js
- test/vaadin-split-panel_test.html
- vaadin-split-panel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-panel/1)
> First implementation + tests

- vaadin-split-panel.html
Did some refactoring and cleanup. I know some of these are a matter of taste, so feel free to open a discussion of any of the changes. 😄
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-panel/5)
> Misc refactoring and cleanup

- demo/index.html
Fixes #11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/12)
> Fix example in IE11

- vaadin-split-layout.html
Fixes #14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/15)
> Fixes for CSS selectors

- demo/index.html
- index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/24)
> webcomponents-lite.js -> webcomponents-lite.min.js

- demo/custom.html
- vaadin-split-layout.html
Connected to #6 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/25)
> Add simplicity to the styles

- bower.json
- demo/common.html
- demo/custom.html
- demo/index.html
- docs/vaadin-split-layout-styling.adoc
- vaadin-split-layout.html
fixes #6
Fixes #22 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/19)
> Custom styles

- vaadin-split-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/28)
> make lint happy

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/29)
> Adding demo for home page in webcomponents.org

- docs/vaadin-split-layout-styling.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/32)
> Fix typo in doc

- .travis.yml
- test/index.html
- test/vaadin-split-layout_test.html
Fixes #37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/38)
> Load mock-interactions.js and mock-touch-interactions.js before webcomponents.js

- .travis.yml
- bower-2.0.json
- bower.json
- demo/common.html
- demo/custom.html
- demo/index.html
- docs/vaadin-split-layout-styling.adoc
- gulpfile.js
- package.json
- test/enable-shadow-dom.js
- test/index.html
- test/vaadin-split-layout_test.html
- vaadin-split-layout.html
- wct.conf-2.0.js
- wct.conf.js
Fixes #40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/47)
> Polymer Hybrid Element Compliant.

- .travis.yml
- test/.eslintrc.json
- test/visual/test.js
The issue:
Same as https://github.com/vaadin/vaadin-input/issues/10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/48)
> Fix visual tests for IE/Edge

- bower-2.0.json
- demo/common.html
- demo/custom.html
- demo/index.html
- demo/integration.html
- test/vaadin-split-layout_test.html
- vaadin-split-layout.html
Fixes #50 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/49)
> Add Google Maps example

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/54)
> Add Polymer 2 badge

- bower.json
Fixes #55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/56)
> Remove test-fixture from bower.json and bump WCT version

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/60)
> Bump polymer-cli: next -> ^0.18.0

- .eslintrc.json
- .travis.yml
- bower.json
- documentation.json
- index.html
- test/vaadin-split-layout_test.html
- vaadin-split-layout.html
Connects to #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/73)
> Convert to pure P2 ES6 class

- bower.json
- demo/index.html
- theme/valo/vaadin-split-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/94)
> Update Valo dependency

- README.md
Fixes #95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/96)
> Fix inline demo polyfill path

- src/vaadin-split-layout.html
- test/vaadin-split-layout_test.html
Fixes #85
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/97)
> Add `splitter-dragend` event API

- src/vaadin-split-layout.html
Fixed #98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/99)
> Enable momentum scrolling on slotted elements on iOS

- bower.json
- theme/material/vaadin-split-layout-styles.html
- theme/material/vaadin-split-layout.html
Connected to vaadin/vaadin-material-styles#49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/110)
> Adding theme/material

- analysis.json
- src/vaadin-split-layout.html
Connected to vaadin/components-team-tasks#403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/119)
> Remove Polymer mention in the API docs [skip ci]

- demo/split-layout-integration-demos.html
Connected to vaadin/components-team-tasks#389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-split-layout/121)
> Drop Polymer-specific iron-resizable-behavior demo [skip ci]

- src/vaadin-split-layout.html
- test/vaadin-split-layout_test.html
- theme/lumo/vaadin-split-layout-styles.html
> Apply RTL logic for resizing

- index.html
- rollup.config.js
- src/vaadin-split-layout.ts
- vaadin-split-layout.html
- vaadin-split-layout.ts
> LitElement conversion part 4: API docs

- src/vaadin-split-layout.html
- test/vaadin-split-layout_test.html
Cherry-pick of https://github.com/vaadin/web-components/pull/3396 for Vaadin 14.
- Cherry-pick
> fix: cleanup slot attribute on removed nodes (CP)
